### ISSUE TITLE
Bugs with encryptpad v0.5.0.2

### ISSUE THREAD

**Issue by cfgnunes** [evpo/snap-for-encryptpad#1]
Hi, @evpo !

I use the Ubuntu 20.04.1. Today, I've tested Encryptpad v0.5.0.2 via Snapcraft.

I noted some issues with this new release:
1) The app doesn't open on Ubuntu using "Wayland";
2) The desktop shortcut doesn't appear on list applications;

Bellow, is the old “snapcraft.yaml” that I wrote for the version v0.5.0.1. Maybe, this script can help you to resolve these problems.
https://github.com/cfgnunes/my-snap-packages/blob/main/encryptpad/snap/snapcraft.yaml

Also, if you prefer, I can request the transfer of Encryptpad management on Scnapcract.io to you (to your account).

Best regards,

**Comment by evpo** [comment]
Hi @cfgnunes ,

Yes, I will make sure it works in your system. I will do a few more iterations and use your script.

I think it would make sense to transfer the ownership.

Thanks,
Evgeny

**Comment by evpo** [comment]
Hi @cfgnunes ,

I uploaded the snap. Please have a look. I verified your  version of Linux and the desktop menu integration.

Cheers,
Evgeny

**Comment by cfgnunes** [comment]
Hi @evpo !

I've tested the issues, and now it's fixed.

Moreover, I've requested the transfer of snap to your account. You can see this process in:
https://forum.snapcraft.io/t/transfer-request-please-transfer-snap-encryptpad-to-user-evpo/31490

Thanks,
Cristiano
